# Generated by Django 3.0.5 on 2025-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='文本内容')),
                ('label1', models.CharField(blank=True, max_length=255, verbose_name='标注1')),
                ('label2', models.CharField(blank=True, max_length=255, verbose_name='标注2')),
                ('label3', models.CharField(blank=True, max_length=255, verbose_name='标注3')),
                ('llm_answer', models.TextField(blank=True, verbose_name='大模型答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '数据记录',
                'verbose_name_plural': '数据记录',
            },
        ),
    ]
