# Generated by Django 3.0.5 on 2025-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='label4',
            field=models.CharField(blank=True, max_length=255, verbose_name='标注4'),
        ),
    ]
